# Generated by Django 3.1.6 on 2021-02-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecore', '0002_auto_20210105_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marchent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marchentName', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
    ]
