# Generated by Django 3.1.6 on 2021-02-04 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecore', '0004_auto_20210204_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RFIDNumber', models.IntegerField(max_length=20)),
                ('leninName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecore.lenin')),
                ('marchent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecore.marchent')),
            ],
        ),
    ]
