# Generated by Django 3.1.6 on 2021-02-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecore', '0005_rfid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfid',
            name='RFIDNumber',
            field=models.IntegerField(),
        ),
    ]
